package com.civicplatform.service;

import com.civicplatform.dto.response.EventMatchingStatsResponse;
import com.civicplatform.entity.Event;
import com.civicplatform.entity.EventInvitationMatchHistory;
import com.civicplatform.entity.EventMatchingRunStats;
import com.civicplatform.repository.EventInvitationMatchHistoryRepository;
import com.civicplatform.repository.EventMatchingRunStatsRepository;
import com.civicplatform.service.dto.InvitationCandidateSnapshot;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

/**
 * Persists and serves statistics/history generated by invitation matching runs.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class EventInvitationStatsService {

    private final EventMatchingRunStatsRepository runStatsRepository;
    private final EventInvitationMatchHistoryRepository matchHistoryRepository;

    /**
     * Persists aggregate run stats and candidate-level score history.
     *
     * @return generated run identifier used to correlate rows
     */
    @Transactional
    @CacheEvict(cacheNames = {"eventInvitationLatestStats", "eventInvitationRunStatsPage"}, allEntries = true)
    public String persistRun(Event event, List<InvitationCandidateSnapshot> snapshots, long durationMs) {
        String runId = UUID.randomUUID().toString();
        LocalDateTime now = LocalDateTime.now();
        int directInvites = (int) snapshots.stream().filter(InvitationCandidateSnapshot::directInvite).count();
        int nurture = snapshots.size() - directInvites;
        double avgRate = snapshots.stream().mapToDouble(InvitationCandidateSnapshot::compositeRate).average().orElse(0.0);
        double maxRate = snapshots.stream().mapToDouble(InvitationCandidateSnapshot::compositeRate).max().orElse(0.0);

        EventMatchingRunStats run = EventMatchingRunStats.builder()
                .event(event)
                .runId(runId)
                .candidateCount(snapshots.size())
                .directInviteCount(directInvites)
                .nurtureCount(nurture)
                .averageCompositeRate(avgRate)
                .maxCompositeRate(maxRate)
                .durationMs(durationMs)
                .createdAt(now)
                .build();
        runStatsRepository.save(run);

        List<EventInvitationMatchHistory> rows = snapshots.stream().map(s -> EventInvitationMatchHistory.builder()
                .event(event)
                .runId(runId)
                .citizenId(s.citizenId())
                .citizenName(s.citizenName())
                .citizenUserType(s.citizenUserType())
                .compositeRate(s.compositeRate())
                .rawScore(s.rawScore())
                .invitationTier(s.invitationTier())
                .priorityFollowup(s.priorityFollowup())
                .selectedForDirectInvite(s.directInvite())
                .createdAt(now)
                .build()).toList();
        matchHistoryRepository.saveAll(rows);

        log.info("Persisted invitation matching run {} for event {} with {} candidates", runId, event.getId(), snapshots.size());
        return runId;
    }

    /**
     * Returns the most recent persisted stats for one event.
     */
    @Transactional(readOnly = true)
    @Cacheable(cacheNames = "eventInvitationLatestStats", key = "#eventId")
    public EventMatchingStatsResponse latestForEvent(Long eventId) {
        return runStatsRepository.findTopByEventIdOrderByCreatedAtDesc(eventId)
                .map(this::toResponse)
                .orElseGet(() -> EventMatchingStatsResponse.builder()
                        .eventId(eventId)
                        .candidateCount(0)
                        .directInviteCount(0)
                        .nurtureCount(0)
                        .averageCompositeRate(0.0)
                        .maxCompositeRate(0.0)
                        .durationMs(0L)
                        .build());
    }

    /**
     * Returns paginated run stats for one event.
     */
    @Transactional(readOnly = true)
    @Cacheable(cacheNames = "eventInvitationRunStatsPage", key = "#eventId + ':' + #pageable.pageNumber + ':' + #pageable.pageSize")
    public Page<EventMatchingStatsResponse> pagedForEvent(Long eventId, Pageable pageable) {
        return runStatsRepository.findByEventIdOrderByCreatedAtDesc(eventId, pageable).map(this::toResponse);
    }

    private EventMatchingStatsResponse toResponse(EventMatchingRunStats row) {
        return EventMatchingStatsResponse.builder()
                .runId(row.getRunId())
                .eventId(row.getEvent().getId())
                .candidateCount(row.getCandidateCount())
                .directInviteCount(row.getDirectInviteCount())
                .nurtureCount(row.getNurtureCount())
                .averageCompositeRate(row.getAverageCompositeRate())
                .maxCompositeRate(row.getMaxCompositeRate())
                .durationMs(row.getDurationMs())
                .createdAt(row.getCreatedAt())
                .build();
    }
}
